# CREATE INDEX
transcriptome: "ref/Callithrix_jacchus/ncbi_dataset/data/GCF_011100555.1/GCF_011100555.1_mCalJa1.2.pat.X_genomic.fna"
gtf: "ref/Callithrix_jacchus/ncbi_dataset/data/GCF_011100555.1/genomic.gtf"
read_length: 100
splici_flank_trim_len: 5

# USE INDEX

# Alevin_fry
alevin_folder: "ref/Callithrix_jacchus/splici_GCF_011100555.1_mCalJa1.2.pat.X"
tx2gene: "ref/Callithrix_jacchus/splici_GCF_011100555.1_mCalJa1.2.pat.X/splici_fl95_t2g_3col.tsv"
transcriptome_splici: "ref/Callithrix_jacchus/splici_GCF_011100555.1_mCalJa1.2.pat.X/splici_fl95.fa"
gene_id_to_name: "ref/Callithrix_jacchus/splici_GCF_011100555.1_mCalJa1.2.pat.X/gene_id_to_name.tsv"
idx_alevin: "ref/Callithrix_jacchus/splici_GCF_011100555.1_mCalJa1.2.pat.X_salmon_index"
#barcode_list: "ref/barcode_lists/sc_5_v3.txt"
#barcode_list: "ref/barcode_lists/sc_3_v2-5_v1_5_v2-HT_v2.txt" # probable same as tutorial

# STARsolo
idx_STAR: "ref/Callithrix_jacchus/GCF_011100555.1_mCalJa1.2.pat.X_star_index"

mt_genes: "ref/GRCh38/mt_genes.txt"
rrna_genes: "ref/GRCh38/ribosome.txt"
