# CREATE INDEX
transcriptome: "ref/mouse/Mus_musculus.GRCm39.dna.primary_assembly.fa"
gtf: "ref/mouse/Mus_musculus.GRCm39.108.gtf"
read_length: 100
splici_flank_trim_len: 5

# USE INDEX

# Alevin_fry
alevin_folder: "ref/mouse/splici_Mus_musculus.GRCm39"
tx2gene: "ref/mouse/splici_Mus_musculus.GRCm39/splici_fl95_t2g_3col.tsv"
transcriptome_splici: "ref/mouse/splici_Mus_musculus.GRCm39/splici_fl95.fa"
gene_id_to_name: "ref/mouse/splici_Mus_musculus.GRCm39/gene_id_to_name.tsv"
idx_alevin: "ref/mouse/splici_Mus_musculus.GRCm39_salmon_index"
#barcode_list: "ref/barcode_lists/sc_5_v3.txt"
#barcode_list: "ref/barcode_lists/sc_3_v2-5_v1_5_v2-HT_v2.txt" # probable same as tutorial

# STARsolo
idx_STAR: "ref/GRCh38/GCF_000001405.40_GRCh38.p14_star_index"

mt_genes: "ref/GRCh38/mt_genes.txt"
rrna_genes: "ref/GRCh38/ribosome.txt"
