# CREATE INDEX
transcriptome: "ref/Macaca_fascicularis/ncbi_dataset/data/GCF_012559485.2/GCF_012559485.2_MFA1912RKSv2_genomic.fna"
gtf: "ref/Macaca_fascicularis/ncbi_dataset/data/GCF_012559485.2/genomic.gtf"
read_length: 100
splici_flank_trim_len: 5

# USE INDEX

# Alevin_fry
alevin_folder: "ref/Macaca_fascicularis/splici_GCF_012559485.2_MFA1912RKSv2"
tx2gene: "ref/Macaca_fascicularis/splici_GCF_012559485.2_MFA1912RKSv2/splici_fl95_t2g_3col.tsv"
transcriptome_splici: "ref/Macaca_fascicularis/splici_GCF_012559485.2_MFA1912RKSv2/splici_fl95.fa"
gene_id_to_name: "ref/Macaca_fascicularis/splici_GCF_012559485.2_MFA1912RKSv2/gene_id_to_name.tsv"
idx_alevin: "ref/Macaca_fascicularis/splici_GCF_012559485.2_MFA1912RKSv2_salmon_index"
#barcode_list: "ref/barcode_lists/sc_5_v3.txt"
#barcode_list: "ref/barcode_lists/sc_3_v2-5_v1_5_v2-HT_v2.txt" # probable same as tutorial

# STARsolo
idx_STAR: "ref/Macaca_fascicularis/GCF_012559485.2_MFA1912RKSv2_star_index"

mt_genes: "ref/GRCh38/mt_genes.txt"
rrna_genes: "ref/GRCh38/ribosome.txt"

