# CREATE INDEX
transcriptome: "ref/chicken/ncbi_dataset/data/GCF_016699485.2/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna"
gtf: "ref/chicken/ncbi_dataset/data/GCF_016699485.2/genomic.gtf"
read_length: 100
splici_flank_trim_len: 5

# USE INDEX

# Alevin_fry
alevin_folder: "ref/chicken/splici_GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b"
tx2gene: "ref/chicken/splici_GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b/splici_fl95_t2g_3col.tsv"
transcriptome_splici: "ref/chicken/splici_GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b/splici_fl95.fa"
gene_id_to_name: "ref/chicken/splici_GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b/gene_id_to_name.tsv"
idx_alevin: "ref/chicken/splici_GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_salmon_index"
#barcode_list: "ref/barcode_lists/sc_5_v3.txt"
#barcode_list: "ref/barcode_lists/sc_3_v2-5_v1_5_v2-HT_v2.txt" # probable same as tutorial

# STARsolo
idx_STAR: "ref/chicken/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_star_index"

mt_genes: "ref/GRCh38/mt_genes.txt"
rrna_genes: "ref/GRCh38/ribosome.txt"

